Repository OmicsML/dance, pull requests merged in 2023-12, with the labels that each got.

#358 new datasets, additional preprocessing methods, and graph constructions
  dance/datasets/multimodality.py
  dance/datasets/spatial.py
  dance/modules/multi_modality/joint_embedding/dcca.py
  dance/modules/multi_modality/joint_embedding/jae.py
  dance/modules/multi_modality/match_modality/cmae.py
  dance/modules/multi_modality/predict_modality/scmm.py
  dance/modules/spatial/spatial_domain/stlearn.py
  dance/transforms/__init__.py
  dance/transforms/cell_feature.py
  dance/transforms/filter.py
  dance/transforms/graph/RESEPT_graph.py
  dance/transforms/graph/__init__.py
  dance/transforms/graph/feature_feature_graph.py
  dance/transforms/graph/scmogcn_graph.py
  dance/transforms/graph/spatial_graph.py
  dance/transforms/graph_construct.py
  dance/transforms/normalize.py
  dance/transforms/preprocess.py
  dance/transforms/pseudo_gen.py
  dance/transforms/sc3_feature.py
  dance/transforms/spatial_feature.py
  dance/utils/matrix.py
  examples/multi_modality/predict_modality/scmogcn.py
  requirements.txt
  setup.cfg
  tests/utils/test_matrix.py
Labels: enhancement, Priority-P0

#380 fix: align `obs_names` of mod2 to mod1 when necessary
  CHANGELOG.md
  dance/datasets/multimodality.py
  dance/modules/multi_modality/predict_modality/cmae.py
  dance/utils/__init__.py
  examples/multi_modality/predict_modality/babel.py
Labels: bug

#388 patchfix: disable windows lint test due to faulty windows img from github action
  .github/workflows/lint.yml
Labels: wontfix
